#!/usr/bin/env bash

DOTFILES_ROOT="$HOME/.dotfiles"

# shellcheck disable=SC1090,SC1091
. "$DOTFILES_ROOT/bin/_common-dependencies"

# shellcheck disable=SC1090,SC1091
. "$DOTFILES_ROOT/bin/_setup-gitconfig"

# shellcheck disable=SC1090,SC1091
. "$DOTFILES_ROOT/bin/_copy-symlinks"

# shellcheck disable=SC1090,SC1091
. "$DOTFILES_ROOT/bin/_editor-config-symlinks"

# shellcheck disable=SC1090,SC1091
. "$DOTFILES_ROOT/bin/_osx-defaults"
